name: Run Load Test on Azure ACI

on:
  push:
    branches:
      - test # Trigger when pushing to 'test' branch

env:
  RESOURCE_GROUP: demoresourcegrp
  ACR_NAME: chausag # Change this to your Azure Container Registry name
  LOCUST_MASTER: locust-master
  LOCUST_WORKER: boomer-worker
  ACI_GROUP: locust-loadtest

jobs:
  deploy-load-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Log in to Azure Container Registry
        run: |
          az acr login --name $ACR_NAME

      - name: Build and Push Docker Images
        run: |
          docker build -t $ACR_NAME.azurecr.io/$LOCUST_MASTER:latest -f Dockerfile.master ./locust
          docker build -t $ACR_NAME.azurecr.io/$LOCUST_WORKER:latest -f Dockerfile.worker ./boomer
          docker push $ACR_NAME.azurecr.io/$LOCUST_MASTER:latest
          docker push $ACR_NAME.azurecr.io/$LOCUST_WORKER:latest

      - name: Deploy Locust Master and Workers to Azure Container Instances
        run: |
          az container create --resource-group $RESOURCE_GROUP --name $ACI_GROUP \
            --image $ACR_NAME.azurecr.io/$LOCUST_MASTER:latest \
            --cpu 2 --memory 4 \
            --registry-login-server $ACR_NAME.azurecr.io \
            --registry-username ${{ secrets.ACR_USERNAME }} \
            --registry-password ${{ secrets.ACR_PASSWORD }} \
            --dns-name-label locust-master-${{ github.run_id }} \
            --ports 8089 \
            --secure-environment-variables EXPECT_WORKERS=2

          az container create --resource-group $RESOURCE_GROUP --name $ACI_GROUP-workers \
            --image $ACR_NAME.azurecr.io/$LOCUST_WORKER:latest \
            --cpu 1 --memory 2 \
            --registry-login-server $ACR_NAME.azurecr.io \
            --registry-username ${{ secrets.ACR_USERNAME }} \
            --registry-password ${{ secrets.ACR_PASSWORD }} \
            --secure-environment-variables LOCUST_MASTER_HOST=http://locust-master-${{ github.run_id }}:8089

      - name: Stream Logs from Locust Master
        run: |
          az container logs --resource-group $RESOURCE_GROUP --name $ACI_GROUP

      - name: Delete ACI After Test
        if: always()
        run: |
          az container delete --resource-group $RESOURCE_GROUP --name $ACI_GROUP --yes
          az container delete --resource-group $RESOURCE_GROUP --name $ACI_GROUP-workers --yes
